### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Cullylondon-Store-Dev---20-March-2022#13]
The images are not reflecting in blog/news page.
https://rb5pgvsc4x37muwl-54946201819.shopifypreview.com/blogs/news/visting-michael-smith
![image](https://user-images.githubusercontent.com/97726944/165935936-9d48ee2e-b06e-4024-a8c5-7179b28e4e19.png)

https://rb5pgvsc4x37muwl-54946201819.shopifypreview.com/blogs/news/at-pigs-ear
![image](https://user-images.githubusercontent.com/97726944/165935893-4248316b-835e-4f6a-bfc9-88da0aed2cac.png)

https://rb5pgvsc4x37muwl-54946201819.shopifypreview.com/blogs/news/visiting-nigel-smith
![image](https://user-images.githubusercontent.com/97726944/165936085-cb1e142c-9484-42f6-8e6b-64c91028b930.png)

https://rb5pgvsc4x37muwl-54946201819.shopifypreview.com/blogs/news/visiting-paul-gay
![image](https://user-images.githubusercontent.com/97726944/165936297-61870d39-c07a-480c-a0fc-5bf0c50ca1da.png)

**Comment by ui-muskandwivedi** [comment]
Images are coming from client old site which is no longer available rn. So Gyanendra sir ask for the images from client for these pages

**Comment by devAlokTripathi** [comment]
![image](https://user-images.githubusercontent.com/100207984/166450366-7f6a8225-d56d-4c60-a2d2-7e560a57f81f.png)
@Shoaibans

**Comment by devAlokTripathi** [comment]
@Shoaibans  clients need  to upload correct 
![image](https://user-images.githubusercontent.com/100207984/166450803-0b2f5579-0c41-492c-adf5-240d0c417971.png)

**Comment by Shoaibans** [comment]
Pending from client end
