### ISSUE TITLE
Filters in mobile & iPad

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Cullylondon-Store-Dev---20-March-2022#15]
The filters are coming in mobile, ipad view & the sortby is not on the left side of the page.

![image](https://user-images.githubusercontent.com/97726944/165945694-7ab74c74-3924-4a54-ae0d-f16d9ef25d0e.png)

![image](https://user-images.githubusercontent.com/97726944/166088912-0bf5f4a3-613b-4723-9064-f7e4e4b2b110.png)

**Comment by devAlokTripathi** [comment]
not required. @Shoaibans
