### ISSUE TITLE
Images overlapping with banners

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Cullylondon-Store-Dev---20-March-2022#18]
The images are overlapping with the banner in homepage mobile (ios)

![image](https://user-images.githubusercontent.com/97726944/165945258-56f4b9ec-9814-4064-aea6-7030e89b3f21.png)

**Comment by ui-muskandwivedi** [comment]
(https://user-images.githubusercontent.com/100340361/165962436-296c563c-c3df-4034-854b-f7543ac6c721.png)
