### ISSUE TITLE
Big Image in iPad homepage

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Cullylondon-Store-Dev---20-March-2022#19]
The image is coming big in homepage iPad.

![image](https://user-images.githubusercontent.com/97726944/166088624-67c6de09-71fa-4fdb-92c1-aa32e4c5fabd.png)

**Comment by ui-muskandwivedi** [comment]
the image is not large, it is the size of this image and we use diffrent size images in this section for design purpose.
