### ISSUE TITLE
Collection name in Link.

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Cullylondon-Store-Dev---20-March-2022#20]
The Collection name in Title, Nav menu & Link are coming different.
In Nav menu the name is showing Outwear but in the collection page the title is Outerwear.
Same in Homepage, showing Outerwear and on redirecting to the collection page the link is showing Outwear.

![image](https://user-images.githubusercontent.com/97726944/166094167-ca66127c-16a3-47e7-8306-99ecabf031a3.png)

![image](https://user-images.githubusercontent.com/97726944/166094236-bb5d0771-f43c-4711-bdd0-fca62092e7f3.png)

![image](https://user-images.githubusercontent.com/97726944/166094246-9a056e2b-5342-4b5b-9fed-142233840d47.png)

![image](https://user-images.githubusercontent.com/97726944/166094277-26e76406-4dae-4e07-8920-9b920929e8f3.png)

Video: https://www.awesomescreenshot.com/video/8676771?key=c17f3655b5d3ada356a296fc98cd0b4d

**Comment by devAlokTripathi** [comment]
![image](https://user-images.githubusercontent.com/100207984/166241327-a0441569-6e25-45a3-8124-fb56322a97c0.png)
