### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Cullylondon-Store-Dev---20-March-2022#3]
The return to login link is missing from the registration page.
https://rb5pgvsc4x37muwl-54946201819.shopifypreview.com/account/register

![image](https://user-images.githubusercontent.com/97726944/165928287-ed296b06-f4b5-416d-82bf-428c4f6b1717.png)

**Comment by devAlokTripathi** [comment]
![image](https://user-images.githubusercontent.com/100207984/166099667-d04c5bd9-d71f-4935-92bc-47fa32d2a803.png)
done

**Comment by Shoaibans** [comment]
![image](https://user-images.githubusercontent.com/97726944/166198210-d1dc04e3-d29e-45c7-bef0-628452093b03.png)

**Comment by devAlokTripathi** [comment]
https://user-images.githubusercontent.com/100207984/166656394-c9af67e4-4648-4faf-bcd3-d63d86f1f872.mp4

**Comment by Shoaibans** [comment]
No need of button, just a link will work.
