### ISSUE TITLE
Link working on double click

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Cullylondon-Store-Dev---20-March-2022#4]
In login page if we click on create account/one link then on first click the form is showing a validation we are redirecting to the registration page on 2nd click.

Video: https://www.awesomescreenshot.com/video/8663379?key=ba62463a176403efd74957e88e7d2cc1

**Comment by devAlokTripathi** [comment]
fixed.

**Comment by devAlokTripathi** [comment]
@Shoaibans  its working in my system need an internal discussion for this so i can check the issue.

**Comment by Shoaibans** [comment]
When the login & registration page is loaded for the first time with empty fields and we click on create one link or Back to login then instead of redirecting to the page it shows the validation & on 2nd click the links work.

Video: https://www.awesomescreenshot.com/video/8744300?key=19263c0caecad6639f75d7c733cf2f1b

**Comment by devAlokTripathi** [comment]
@Shoaibans  please check issue fixed.

**Comment by devAlokTripathi** [comment]
@Shoaibans issue fixed. please check
