### ISSUE TITLE
Header alignment

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Cullylondon-Store-Dev---20-March-2022#7]
The header menus/ icons are not properly aligned.

![image](https://user-images.githubusercontent.com/97726944/165930887-7ee7e510-110e-4ae7-8313-dec2c0a17164.png)

**Comment by Shoaibans** [comment]
Not fixed.

![image](https://user-images.githubusercontent.com/97726944/166198597-7ef5fd6f-8dff-4569-b0da-e061a99fe279.png)

**Comment by ui-muskandwivedi** [comment]
![2022-05-02 (7)](https://user-images.githubusercontent.com/100340361/166258862-13f802b7-a21d-4d4f-90f6-0b1d0b714d96.png)

**Comment by Shoaibans** [comment]
Alignment is not proper.
![image](https://user-images.githubusercontent.com/97726944/166635260-df22d5c4-d00c-4e2d-96b5-a3b2c8889b1e.png)

**Comment by ui-muskandwivedi** [comment]
can't remove more left right spacing because it leads to horizontal scrolling
