### ISSUE TITLE
Sortby in collection page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Cullylondon-Store-Dev---20-March-2022#8]
The sortby is clickable from the empty space between title & sortby.
https://rb5pgvsc4x37muwl-54946201819.shopifypreview.com/collections/outwear

Video: https://www.awesomescreenshot.com/video/8663667?key=8f8d8bc228f4bb620d6d8329fa1b7c52

**Comment by devAlokTripathi** [comment]
@Shoaibans fixed please check 
![image](https://user-images.githubusercontent.com/100207984/166258724-96c4b66b-facb-48c1-81d0-77f6f11ab7a5.png)
