### ISSUE TITLE
Filter name not reflecting

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---Cullylondon-Store-Dev---20-March-2022#9]
The applied filter name should be displayed in the box.
https://rb5pgvsc4x37muwl-54946201819.shopifypreview.com/collections/outwear

![image](https://user-images.githubusercontent.com/97726944/165931859-27e0b18d-ad20-4a7a-addb-fcbfb808fd11.png)

Video: https://www.awesomescreenshot.com/video/8663711?key=c71af2e35e33aa2249a9390c42785d50

**Comment by ui-muskandwivedi** [comment]
Theme dosesn't have this functionality
